import { shiftInterface, userInterface } from "@/types"
import avatar1 from "../../public/avatars/avatar1.png"
import avatar2 from "../../public/avatars/avatar2.png"
import avatar3 from "../../public/avatars/avatar3.png"

export const mockShiftData: shiftInterface[] = [
  {
    id: 1,
    user: {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      role: 0,
      hoursWorked: 24,
      profileImage: avatar1,
    },
    competencies: [],
    attributes: [],
    start: "2024-12-04T07:00:00.232Z",
    end: "2024-12-04T15:20:00.232Z",
    breakPaid: "0",
    breakUnpaid: "30",
    specialCode: "specialCode",
    isShiftCompensated: true,
    currency: 974,
    salary: "123",
    exceedsMaxHours: true,
    status: 0,
    shiftType: 1,
  },
  {
    id: 2,
    user: {
      id: 2,
      firstName: "Sara",
      lastName: "Root",
      role: 0,
      hoursWorked: 38,
      profileImage: avatar2,
    },
    competencies: [],
    attributes: [],
    start: "2024-12-04T15:00:00.232Z",
    end: "2024-12-04T15:10:00.232Z",
    breakPaid: null,
    breakUnpaid: null,
    specialCode: "specialCode",
    isShiftCompensated: true,
    currency: null,
    salary: null,
    exceedsMaxHours: true,
    status: 1,
    shiftType: 2,
  },
  {
    id: 3,
    user: {
      id: 3,
      firstName: "Lera",
      lastName: "Charlton",
      role: 1,
      hoursWorked: 38,
      profileImage: avatar3,
    },
    competencies: [],
    attributes: [],
    start: "2024-12-04T15:00:00.232Z",
    end: "2024-12-04T15:10:00.232Z",
    breakPaid: "0",
    breakUnpaid: "30",
    specialCode: "specialCode",
    isShiftCompensated: true,
    currency: 840,
    salary: "10",
    exceedsMaxHours: true,
    status: 0,
    shiftType: 6,
  },
  {
    id: 4,
    user: {
      id: 4,
      firstName: "Ben",
      lastName: "Doe",
      role: 1,
      hoursWorked: 38,
      profileImage: null,
    },
    competencies: [],
    attributes: [],
    start: "2024-12-04T15:00:00.232Z",
    end: "2024-12-04T15:10:00.232Z",
    breakPaid: "0",
    breakUnpaid: "30",
    specialCode: "specialCode",
    isShiftCompensated: true,
    currency: 840,
    salary: "10",
    exceedsMaxHours: true,
    status: 0,
    shiftType: 4,
  },
]

export const mockUsersData: userInterface[] = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    role: 0,
    hoursWorked: 24,
    profileImage: avatar1,
  },
  {
    id: 2,
    firstName: "Sara",
    lastName: "Root",
    role: 0,
    hoursWorked: 38,
    profileImage: avatar2,
  },
  {
    id: 3,
    firstName: "Lera",
    lastName: "Charlton",
    role: 1,
    hoursWorked: 38,
    profileImage: avatar3,
  },
  {
    id: 4,
    firstName: "Ben",
    lastName: "Doe",
    role: 1,
    hoursWorked: 38,
    profileImage: null,
  },
]
