import { shiftInterface } from "@/types"

export const mockShiftData: shiftInterface[] = [
  {
    id: 1,
    user: {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      role: 0,
      hoursWorked: "hoursWorked",
      profileImage: "profileImage",
    },
    competencies: [],
    attributes: [],
    start: "2024-12-04T07:00:00.232Z",
    end: "2024-12-04T15:20:00.232Z",
    breakPaid: "0",
    breakUnpaid: "30",
    specialCode: "specialCode",
    isShiftCompensated: true,
    currency: 974,
    salary: "123",
    exceedsMaxHours: true,
    status: 0,
    shiftType: 1,
  },
  {
    id: 2,
    user: {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      role: 0,
      hoursWorked: "hoursWorked",
      profileImage: "profileImage",
    },
    competencies: [],
    attributes: [],
    start: "2024-12-04T15:00:00.232Z",
    end: "2024-12-04T15:10:00.232Z",
    breakPaid: null,
    breakUnpaid: null,
    specialCode: "specialCode",
    isShiftCompensated: true,
    currency: null,
    salary: null,
    exceedsMaxHours: true,
    status: 1,
    shiftType: 2,
  },
  {
    id: 3,
    user: {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      role: 0,
      hoursWorked: "hoursWorked",
      profileImage: "profileImage",
    },
    competencies: [],
    attributes: [],
    start: "2024-12-04T15:00:00.232Z",
    end: "2024-12-04T15:10:00.232Z",
    breakPaid: "0",
    breakUnpaid: "30",
    specialCode: "specialCode",
    isShiftCompensated: true,
    currency: 840,
    salary: "10",
    exceedsMaxHours: true,
    status: 0,
    shiftType: 6,
  },
  {
    id: 4,
    user: {
      id: 1,
      firstName: "John",
      lastName: "Doe",
      role: 0,
      hoursWorked: "hoursWorked",
      profileImage: "profileImage",
    },
    competencies: [],
    attributes: [],
    start: "2024-12-04T15:00:00.232Z",
    end: "2024-12-04T15:10:00.232Z",
    breakPaid: "0",
    breakUnpaid: "30",
    specialCode: "specialCode",
    isShiftCompensated: true,
    currency: 840,
    salary: "10",
    exceedsMaxHours: true,
    status: 0,
    shiftType: 4,
  },
]
