import { fullUserInfoInterface, shiftInterface, userInterface } from "@/types"
import avatar1 from "../../public/avatars/avatar1.png"
import avatar2 from "../../public/avatars/avatar2.png"
import avatar3 from "../../public/avatars/avatar3.png"
import { ShiftTimingOptions, ShiftType, UserRoles } from "@/types/enums"

export const mockShiftData: shiftInterface[] = [
  {
    id: 1,
    userId: 1,
    competencies: [],
    attributes: [],
    date: "2024-12-04",
    start: "2024-12-04T07:00:00",
    end: "2024-12-04T15:20:00",
    breakPaid: 0,
    breakUnpaid: 30,
    specialCode: "specialCode",
    isShiftCompensated: true,
    status: 0,
    shiftType: 1,
    shiftLength: 0,
  },
  {
    id: 2,
    userId: 2,
    competencies: [],
    attributes: [],
    date: "2024-12-04",
    start: "2024-12-04T07:00:00",
    end: "2024-12-04T15:20:00",
    breakPaid: 0,
    breakUnpaid: 30,
    specialCode: "specialCode",
    isShiftCompensated: true,
    status: 0,
    shiftType: 1,
    shiftLength: 0,
  },
]

export const mockFullUserData: fullUserInfoInterface[] = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    role: 0,
    hoursWorked: 24,
    profileImage: avatar1,
    currency: 974,
    salary: "123",
    shifts: [mockShiftData[0]],
  },
  {
    id: 2,
    firstName: "Sara",
    lastName: "Root",
    role: 0,
    hoursWorked: 38,
    profileImage: avatar2,
    currency: 974,
    salary: "123",
    shifts: [mockShiftData[1]],
  },
  {
    id: 3,
    firstName: "Lera",
    lastName: "Charlton",
    role: 1,
    hoursWorked: 38,
    currency: 974,
    salary: "123",
    profileImage: avatar3,
    shifts: [],
  },
  {
    id: 4,
    firstName: "Ben",
    lastName: "Doe",
    role: 1,
    hoursWorked: 38,
    profileImage: null,
    currency: 974,
    salary: "123",
    shifts: [],
  },
]

export const shiftTypeOptions = [
  { value: ShiftType.CASH_REGISTER, label: "Cash register" },
  { value: ShiftType.VACATION, label: "Vacation" },
  { value: ShiftType.RESTORATION, label: "Restoration" },
  { value: ShiftType.CLOSURE, label: "Closure" },
  { value: ShiftType.TRUCK, label: "Truck" },
  { value: ShiftType.OPENING, label: "Opening" },
  { value: ShiftType.SICK_LEAVE, label: "Sick leave" },
]

export const competenciesOptions = [
  { value: "Competency 1", label: "Competency 1" },
  { value: "Competency 2", label: "Competency 2" },
  { value: "Competency 3", label: "Competency 3" },
  { value: "Competency 4", label: "Competency 4" },
  { value: "Competency 5", label: "Competency 5" },
  { value: "Competency 6", label: "Competency 6" },
  { value: "Competency 7", label: "Competency 7" },
]

export const attributesOptions = [
  { value: "Attribute 1", label: "Attribute 1" },
  { value: "Attribute 2", label: "Attribute 2" },
  { value: "Attribute 3", label: "Attribute 3" },
  { value: "Attribute 4", label: "Attribute 4" },
  { value: "Attribute 5", label: "Attribute 5" },
  { value: "Attribute 6", label: "Attribute 6" },
  { value: "Attribute 7", label: "Attribute 7" },
]

type startTimeOptionsType = {
  value: ShiftTimingOptions
  label: string
  start: string
  end: string
}

export const shiftTimingOptions: startTimeOptionsType[] = [
  { value: ShiftTimingOptions.MORNING_SHIFT, label: "Morning shift", start: "06:00", end: "14:00" },
  { value: ShiftTimingOptions.DAY_SHIFT, label: "Day shift", start: "11:00", end: "19:00" },
  { value: ShiftTimingOptions.EVENING_SHIFT, label: "Evening shift", start: "14:00", end: "22:00" },
]

export const specialCodeOptions = [
  { value: "Code 1", label: "Code 1" },
  { value: "Code 2", label: "Code 2" },
  { value: "Code 3", label: "Code 3" },
  { value: "Code 4", label: "Code 4" },
  { value: "Code 5", label: "Code 5" },
  { value: "Code 6", label: "Code 6" },
  { value: "Code 7", label: "Code 7" },
]

export const mockUsersData: userInterface[] = [
  {
    id: 1,
    firstName: "Alice",
    lastName: "Smith",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 90,
    profileImage: "https://example.com/profile1",
    currency: 974,
    salary: "123",
  },
  {
    id: 2,
    firstName: "Bob",
    lastName: "Johnson",
    role: UserRoles.STUDENT,
    hoursWorked: 20,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 3,
    firstName: "Charlie",
    lastName: "Williams",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 35,
    profileImage: "https://example.com/profile3",
    currency: 974,
    salary: "123",
  },
  {
    id: 4,
    firstName: "Diana",
    lastName: "Brown",
    role: UserRoles.STUDENT,
    hoursWorked: 60,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 5,
    firstName: "Eve",
    lastName: "Jones",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 30,
    profileImage: "https://example.com/profile5",
    currency: 974,
    salary: "123",
  },
  {
    id: 6,
    firstName: "Frank",
    lastName: "Garcia",
    role: UserRoles.STUDENT,
    hoursWorked: 25,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 7,
    firstName: "Grace",
    lastName: "Martinez",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 40,
    profileImage: "https://example.com/profile7",
    currency: 974,
    salary: "123",
  },
  {
    id: 8,
    firstName: "Hank",
    lastName: "Davis",
    role: UserRoles.STUDENT,
    hoursWorked: 10,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 9,
    firstName: "Ivy",
    lastName: "Lopez",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 16,
    profileImage: "https://example.com/profile9",
    currency: 974,
    salary: "123",
  },
  {
    id: 10,
    firstName: "Jack",
    lastName: "Gonzalez",
    role: UserRoles.STUDENT,
    hoursWorked: 18,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 11,
    firstName: "Karen",
    lastName: "Wilson",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 19,
    profileImage: "https://example.com/profile11",
    currency: 974,
    salary: "123",
  },
  {
    id: 12,
    firstName: "Leo",
    lastName: "Anderson",
    role: UserRoles.STUDENT,
    hoursWorked: 26,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 13,
    firstName: "Mia",
    lastName: "Thomas",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 45,
    profileImage: "https://example.com/profile13",
    currency: 974,
    salary: "123",
  },
  {
    id: 14,
    firstName: "Nina",
    lastName: "Taylor",
    role: UserRoles.STUDENT,
    hoursWorked: 60,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 15,
    firstName: "Oliver",
    lastName: "Moore",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 50,
    profileImage: "https://example.com/profile15",
    currency: 974,
    salary: "123",
  },
  {
    id: 16,
    firstName: "Paula",
    lastName: "Jackson",
    role: UserRoles.STUDENT,
    hoursWorked: 25,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 17,
    firstName: "Quinn",
    lastName: "White",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 33,
    profileImage: "https://example.com/profile17",
    currency: 974,
    salary: "123",
  },
  {
    id: 18,
    firstName: "Ryan",
    lastName: "Harris",
    role: UserRoles.STUDENT,
    hoursWorked: 45,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 19,
    firstName: "Sophia",
    lastName: "Martin",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 35,
    profileImage: "https://example.com/profile19",
    currency: 974,
    salary: "123",
  },
  {
    id: 20,
    firstName: "Tom",
    lastName: "Thompson",
    role: UserRoles.STUDENT,
    hoursWorked: 20,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 21,
    firstName: "Uma",
    lastName: "Martinez",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 15,
    profileImage: "https://example.com/profile21",
    currency: 974,
    salary: "123",
  },
  {
    id: 22,
    firstName: "Victor",
    lastName: "Clark",
    role: UserRoles.STUDENT,
    hoursWorked: 12,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 23,
    firstName: "Wendy",
    lastName: "Rodriguez",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 45,
    profileImage: "https://example.com/profile23",
    currency: 974,
    salary: "123",
  },
  {
    id: 24,
    firstName: "Xander",
    lastName: "Lewis",
    role: UserRoles.STUDENT,
    hoursWorked: 8,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 25,
    firstName: "Yara",
    lastName: "Lee",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 25,
    profileImage: "https://example.com/profile25",
    currency: 974,
    salary: "123",
  },
  {
    id: 26,
    firstName: "Zoe",
    lastName: "Walker",
    role: UserRoles.STUDENT,
    hoursWorked: 90,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 27,
    firstName: "Adam",
    lastName: "Hall",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 30,
    profileImage: "https://example.com/profile27",
    currency: 974,
    salary: "123",
  },
  {
    id: 28,
    firstName: "Bella",
    lastName: "Allen",
    role: UserRoles.STUDENT,
    hoursWorked: 5,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
  {
    id: 29,
    firstName: "Cody",
    lastName: "Young",
    role: UserRoles.EMPLOYEE,
    hoursWorked: 20,
    profileImage: "https://example.com/profile29",
    currency: 974,
    salary: "123",
  },
  {
    id: 30,
    firstName: "Daisy",
    lastName: "King",
    role: UserRoles.STUDENT,
    hoursWorked: 26,
    profileImage: null,
    currency: 974,
    salary: "123",
  },
]

export const mockUserOptions = mockUsersData.map(user => ({
  value: user.id,
  label: `${user.firstName} ${user.lastName}`,
  hoursWorked: user.hoursWorked,
}))
